# Generated by Django 5.0.6 on 2024-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='', upload_to='destination/'),
            preserve_default=False,
        ),
    ]
