# Generated by Django 5.0.6 on 2024-06-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destinations',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='travelx.destination'),
            preserve_default=False,
        ),
    ]
