# Generated by Django 5.0.6 on 2024-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
