# Generated by Django 5.0.6 on 2024-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0002_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='about_us/'),
        ),
    ]
