# Generated by Django 5.0.6 on 2024-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0002_remove_aboutus_banner_remove_blog_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
