# Generated by Django 5.0.6 on 2024-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0003_alter_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='fav_icon',
            field=models.ImageField(upload_to='site'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='site'),
        ),
    ]
