# Generated by Django 5.0.6 on 2024-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0005_banner_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
