# Generated by Django 5.0.6 on 2024-05-17 03:35

import django.core.validators
import django.utils.timezone
import travelx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0006_testimonial_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be exactly 10 digits and numeric.'), travelx.models.validate_exact_length]),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be exactly 10 digits'), travelx.models.validate_exact_length]),
        ),
    ]
