# Generated by Django 5.0.6 on 2024-06-01 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelx', '0007_contact_date_alter_contact_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be exactly 10 digits and numeric.')]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='duration',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='group_size',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be exactly 10 digits')]),
        ),
    ]
